---
application:
  name: "ironautocompounder"
  project: "IronAutoCompounder"
  organization: "QoveryCommunity"
routers:
- name: "main-ironautocompounder"
  routes:
  - application_name: "ironautocompounder"
    paths:
    - "/*"
